# Generated by Django 5.2.4 on 2025-08-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Introducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_camisa', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('local_nascimento', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='media/jogadores')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('campeonato', models.CharField(choices=[('BRASILEIRÃO', 'Brasileirão'), ('LIBERTADORES', 'Libertadores')], default='Amistoso')),
                ('estadio', models.CharField()),
                ('time_casa', models.CharField()),
                ('time_visitante', models.CharField()),
                ('placar_casa', models.IntegerField(blank=True)),
                ('placar_visitante', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.TextField()),
            ],
        ),
    ]
