# Generated by Django 5.2.4 on 2025-08-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(default='Atacante', max_length=50),
        ),
    ]
