# Generated by Django 5.2.4 on 2025-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_jogador_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('VOL', 'Volante'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Treinador')], default='Atacante'),
        ),
    ]
