# Generated by Django 5.2.4 on 2025-08-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_jogador_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='jogadores/'),
        ),
    ]
