# Generated by Django 5.2.4 on 2025-08-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_jogador_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('resumo', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='noticias/')),
            ],
        ),
    ]
