# Generated by Django 5.2.4 on 2025-08-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('campeonato', models.CharField(choices=[('BRASILEIRÃO', 'Brasileirão'), ('LIBERTADORES', 'Libertadores')], default='Amistoso')),
                ('estadio', models.CharField()),
                ('time_casa', models.CharField()),
                ('time_visitante', models.CharField()),
            ],
        ),
    ]
